<a href="https://colab.research.google.com/github/aya-soghayyer/Juno-project/blob/main/Copy_of_%F0%9F%90%BC_Section_1_Part_6_Introduction_to_Pandas_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Section 1 - Part 6: Introduction to Pandas Basics

Pandas is a powerful Python library for data manipulation and analysis, widely used in data science and machine learning. It provides data structures like Series and DataFrames, which make handling structured data intuitive and efficient.

## What is Pandas?
- **Overview**:
  - Pandas is an open-source library built on top of NumPy, designed for data analysis and manipulation.
  - It provides two primary data structures: **Series** (1D labeled array) and **DataFrame** (2D table-like structure).
  - **Applications**:
    - **Data Cleaning**: Handle missing data, filter rows, and transform datasets.
    - **Data Analysis**: Perform statistical analysis, grouping, and aggregation.
    - **Data Visualization**: Integrate with Matplotlib for plotting data.
    - **Data Import/Export**: Read/write data in formats like CSV, Excel, JSON, and SQL.

- **Why Use Pandas?**
  - **Ease of Use**: Intuitive syntax for manipulating tabular data, similar to spreadsheets or SQL tables.
  - **Flexibility**: Supports a wide range of data operations, from simple filtering to complex joins.
  - **Performance**: Optimized for large datasets with efficient memory usage and fast operations.
  - **Integration**: Works seamlessly with other Python libraries like NumPy, Matplotlib, and Scikit-learn.
  - **Community Support**: Extensive documentation and a large community for troubleshooting and learning.

- **Setting Up Pandas**
  - **Installation**:
    - For local environments, install Pandas using `pip install pandas`.
    - In Google Colab, Pandas is pre-installed, so no additional setup is needed.
    - Verify installation by running `import pandas as pd; print(pd.__version__)` to check the Pandas version.
  - **Dependencies**:
    - Pandas requires NumPy, which is also pre-installed in Colab.
    - Optional: Install `openpyxl` or `xlrd` for Excel file support, or `sqlalchemy` for SQL database interactions.
  - **Getting Started**:
    - Import Pandas with `import pandas as pd`.
    - Create a DataFrame from a dictionary, list, or external file (e.g., CSV).
    - Use Jupyter Notebooks or Colab for interactive data exploration.

## Watch: Getting Started with Pandas
Below is a beginner-friendly video that introduces Pandas and its core functionalities in Jupyter Notebooks.

In [ ]:
#@title Understanding Pandas in Jupyter Notebooks
from IPython.display import IFrame, Image
try:
  display(IFrame("https://www.youtube.com/embed/CmorAWRsCAw", width=560, height=315))
except:
  display(Image(url="https://img.youtube.com/vi/CmorAWRsCAw/0.jpg"))

## Activity: Your First Pandas DataFrame
In this activity, you will create a Pandas DataFrame in the provided code cell below. Your task is to:
- Create a dictionary with two keys: `name` (containing at least three names as strings) and `age` (containing corresponding ages as integers).
- Convert the dictionary into a Pandas DataFrame using `pd.DataFrame()`.
- Display the DataFrame using `print()` or `display()`.
- Add a new column named `city` with city names for each person.

**Instructions:**
1. Write your code in the cell below.
2. Ensure you import Pandas and create the DataFrame as specified.
3. Run the cell to display your DataFrame.
4. Run the "Check Your Work" cell to verify your output.

**Example Code:**
```python
import pandas as pd
data = {'name': ['Alice', 'Bob', 'Charlie'], 'age': [25, 30, 35]}
df = pd.DataFrame(data)
df['city'] = ['New York', 'London', 'Paris']
display(df)
```

### Task 1: Create a DataFrame
Create a Pandas DataFrame from a dictionary with columns `product` (strings), `price` (floats), and `quantity` (integers) with at least 4 rows. Display the DataFrame.

**Example:**
```python
import pandas as pd
data = {'product': ['Apple', 'Banana', 'Orange', 'Mango'], 'price': [1.5, 0.5, 0.75, 2.0], 'quantity': [10, 20, 15, 5]}
df = pd.DataFrame(data)
display(df)
```

In [ ]:
# Task 1: Create a DataFrame
# - Create a dictionary with 'product', 'price', and 'quantity' columns
# - Convert to a DataFrame with at least 4 rows
# - Display the DataFrame
import pandas as pd
data = {'product': ['Apple', 'Banana', 'Orange', 'Mango'], 'price': [1.5, 0.5, 0.75, 2.0], 'quantity': [10, 20, 15, 5]}
df = pd.DataFrame(data)
display(df)

  product  price  quantity
0   Apple   1.50        10
1  Banana   0.50        20
2  Orange   0.75        15
3   Mango   2.00         5

### Task 2: Add a Total Cost Column
Using the DataFrame from Task 1, add a new column `total_cost` calculated as `price * quantity`. Display the updated DataFrame.

**Example:**
```python
df['total_cost'] = df['price'] * df['quantity']
display(df)
```

In [ ]:
# Task 2: Add a total_cost column
# - Use the DataFrame from Task 1
# - Add a 'total_cost' column (price * quantity)
# - Display the updated DataFrame
df['total_cost'] = df['price'] * df['quantity']
display(df)

  product  price  quantity  total_cost
0   Apple   1.50        10       15.00
1  Banana   0.50        20       10.00
2  Orange   0.75        15       11.25
3   Mango   2.00         5       10.00

### Task 3: Filter and Sort
Filter the DataFrame from Task 2 to include only rows where `total_cost` is greater than 50, then sort by `total_cost` in descending order. Display the result.

**Example:**
```python
filtered_df = df[df['total_cost'] > 50].sort_values(by='total_cost', ascending=False)
display(filtered_df)
```

In [ ]:
# Task 3: Filter and sort
# - Use the DataFrame from Task 2
# - Filter rows where total_cost > 50
# - Sort by total_cost in descending order
# - Display the filtered and sorted DataFrame
filtered_df = df[df['total_cost'] >50 ].sort_values(by = 'total_cost' , ascending= False)
display(filtered_df)

Empty DataFrame
Columns: [product, price, quantity, total_cost]
Index: []

In [ ]:
#@title Peer Evaluation Check Run the cell below to verify all three tasks. You will earn 1 point per task (3 points total). The check assumes the three code cells above this one contain your solutions.
from IPython.display import display, Markdown
from IPython.display import display, Markdown
import pandas as pd

# Initialize scores dictionary if not already present
if 'scores' not in globals():
    scores = {}

def check_pandas_tasks():
    score = 0
    feedback = []

    try:
        # Task 1: Check DataFrame creation
        if 'df' in globals():
            has_product = 'product' in df.columns and df['product'].dtype == object
            has_price = 'price' in df.columns and df['price'].dtype == float
            has_quantity = 'quantity' in df.columns and df['quantity'].dtype == int
            has_min_rows = len(df) >= 4
            if has_product and has_price and has_quantity and has_min_rows:
                score += 1
                feedback.append("- ✅ Task 1 Passed: DataFrame created with 'product', 'price', and 'quantity' columns and at least 4 rows.")
            else:
                missing = []
                if not has_product:
                    missing.append("'product' column with string values")
                if not has_price:
                    missing.append("'price' column with float values")
                if not has_quantity:
                    missing.append("'quantity' column with integer values")
                if not has_min_rows:
                    missing.append("at least 4 rows")
                feedback.append(f"- ❌ Task 1 Failed: DataFrame missing {', '.join(missing)}.")
        else:
            feedback.append("- ❌ Task 1 Failed: No DataFrame 'df' found. Ensure you created and displayed a DataFrame in Task 1.")

        # Task 2: Check total_cost column
        if 'df' in globals() and 'total_cost' in df.columns:
            if all(df['total_cost'] == df['price'] * df['quantity']):
                score += 1
                feedback.append("- ✅ Task 2 Passed: 'total_cost' column added correctly.")
            else:
                feedback.append("- ❌ Task 2 Failed: 'total_cost' column missing or incorrectly calculated.")
        else:
            feedback.append("- ❌ Task 2 Failed: No DataFrame with 'total_cost' column found. Ensure you added the column in Task 2.")

        # Task 3: Check filtering and sorting
        if 'filtered_df' in globals():
            is_filtered = all(filtered_df['total_cost'] > 50)
            is_sorted = filtered_df['total_cost'].is_monotonic_decreasing
            if is_filtered and is_sorted:
                score += 1
                feedback.append("- ✅ Task 3 Passed: DataFrame correctly filtered (total_cost > 50) and sorted by total_cost descending.")
            else:
                feedback.append("- ❌ Task 3 Failed: DataFrame not correctly filtered or sorted.")
        else:
            feedback.append("- ❌ Task 3 Failed: No filtered and sorted DataFrame 'filtered_df' found. Ensure you created it in Task 3.")

        # Display the final DataFrame if all tasks passed
        if score == 3 and 'filtered_df' in globals():
            display(filtered_df)

    except Exception as e:
        feedback.append(f"- ❌ An error occurred: {str(e)}. Ensure your code runs without errors in all task cells.")
        score = 0

    # Update total score
    scores['pandas_tasks_activity'] = score

    # Provide final feedback
    final_message = "**Pandas Tasks Peer Evaluation Feedback:**\n\n" + "\n".join(feedback)
    final_message += f"\n\n**Total Score: {score}/3**"

    display(Markdown(final_message))

check_pandas_tasks()

Empty DataFrame
Columns: [product, price, quantity, total_cost]
Index: []

**Pandas Tasks Peer Evaluation Feedback:**

- ✅ Task 1 Passed: DataFrame created with 'product', 'price', and 'quantity' columns and at least 4 rows.
- ✅ Task 2 Passed: 'total_cost' column added correctly.
- ✅ Task 3 Passed: DataFrame correctly filtered (total_cost > 50) and sorted by total_cost descending.

**Total Score: 3/3**